<!doctype html>
<html lang="en"><head>
<title>A WILD ??? APPEARED...</title>
<link rel="shortcut icon" type="image/x-icon" href="../../mball.ico" />
<style type="text/css">
#missingno{
margin: 20% auto;
width: auto;
text-align: center;
font-family: 'Consolas';
}

a{
    color: #000000;
}
</style>
</head>

<body>

<!-- 
                                                            
                                              .=..,.    ...,~.                    ........................ ... .,.....                      
                                              .~=~:.    ....~,.             ..........,....,...........8........MO8....                     
                                              .:..,.    ,::+,. .           :,:,,,,.,ZN....7::::,,,..:::~........O8I$8..                     
                          . ...          ...  ......    .........  ........,,,,,,,~OD8....?,:::,,,..$N8$........OZZ8...                     
                         ...:::          ...  .7.... .   ..=:~,.. .=====~I7:~=,.,.$OZZ$$=~,,,.,,,.?ZD8ON7.......D$778...    ,.. .           
                         .....,          ,.....++.... . ......+.. .~~++=++===?O8O8$ZZ$I7=:=?I=??II78??..$... ...8NND$,. .,,  . .            
          ...            ....,:    ......,.....M=++.,...~+++.=~....:....$I==....,=NOZ$7??=~=+..?+,$OZOOON.,,...,DDNZ7...?8Z...........      
          .....          ...,..     .==........8+:?..... ..,,+=.........DZ.,,,,...DD87I+=+?=I,:~=.$$~=?,Z.....I?8N88O..,DDN,,?I,D,?7..      
         ......      .. ........,   :++..,.....DOD?........,=+~..$Z,?+==D7I7:=~=:,O+=++=:,I:.:,==+??+?+~+....,IZMMNO7,..8=, . ..:.....      
       .. ...,..............:.,.. ..OND88Z,...,DDNM.,?..+=,,I.=.+8$=++====~~=~?7$7+=++=~,,:,,..+..+,.,8OI~=.,.D8$ZZ$$.D,INO?,:..$+.... ..   
      .. .$Z.8.. ..,......:D...:,.  ?DDD8Z..,:78NMM.....=+=II8Z=$77~+?++7I?~~=:~,..............$77Z.NZ7$:=....D$ZD$Z7~,.$D8, ..,...,.. . ,. 
     ......,,=.....:......I8D8I:,. .:888O:..,:7ODNM:I...=?I$I78,.O$~$$Z++7Z7,...=?I:,::........$7Z,~~:OI?=7,.++I$Z...IZ8O8N,.~=.7.....      
    ......~+:?.~,..:.....D$=887::. ..,:,::....+=~=$...,~I7I8ZI$Z=$$+I78OZZ$Z$ZZZ??Z:$$$,,,I..?I=7..DNNIZ=+~=.N$7$Z~.,DMZ?7,N,,........      
.....     ........~~...:....+I,..,~~7:,,,,...,.::,:,.?:==+~++=$+II7777ZZ$$$Z7$Z$I?Z:::,~=~~=:~==7$Z8888OZDOZ~~Z+Z?~+I$NNZI.I.....   .       
..... .   .....O=:ND=..:.....:....D87:,,,,,.,,=:~~=7?=~~=..,~~OII+?+77$OZI???$Z$IIO,~:,====++?II$$ZOO88OOD88+N8+O=~~I7ONM$:?,......,..      
.....     .....,+DON=........,....DD7~:,:?IZZ7+I7I777DDDZ+I7I$IZ???==,8MNNNDD8ZZOOOOZ77ZZZ$7777$$$$$ZOZZ$NMDNND++~~:?IIOMN~N=Z$$$~I?+.      
 ...,..:~.,=,.,+ZZ$N~...,,,.,.....MDD8Z7I7I8ZO77DNNNDNNZ7INDNDZ7I7$$7?88DDDDNDNZ$+?++Z+=$7Z$$7$$$ZZZOZZZ7DD8MNNI==::=II7DN8DM8NOZZDDD,      
..... . ......,...........Z$:..,,.ZDNN7ZN8MOZ7NDNZN8ZDNNODNNNDN8$D8ZZOONNNMMMM$7II==~~NMMM$$7777MMM87ZMMDMMM.$DNNZ=?+7N++++OZMM7$$ON8.      
...       ..................ZOON+=:.?ZDDDNNMNMNNNNNNNNNNNNNNNNNNNNNNNMMNM77I?7I7=+D$~=~=7+~~+IIINMMMI8MNMNDNMM7?7~,:,~+I7ZNM+..,++....      
.         ..    ...,......,:====?DNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNM$O7+I,.,$NI7$$$$$O$$7IIDMMO??$$+~?OMMN?I?:::~=?I78NNN... ....      
               ...:~==I88DO=+=++8DNNNNNNNNNNNNNNNNNNNNNNNNNDDDOIII??777?$I~==:8877NIN$ZZZ$7$$$8$MM7$III777I788M7IZ::::~+I77DND...           
               ...,::~+ZO8+:,DDDNDDDDDDDNNNNNNNNNNNNNNNNNDNDO?+=+~~+=DMMM+III$7III7=II7$$I7777$~MM++=+?I77I$Z88$ZD=,:~:=II$ZNDO..           
               ....,,,,~+,,,8DNNI?+??IZDDNNNNNNNNNNNNNNNNDO+?+~~~::,,~DNNMMNM87???I???II$7++??:NM8:,,,:II77?~$7I~+I~$I++I~$ZND=.N     ...   
               . ..+ZZ+==~~==?DD++====+?$DNNNNNNNNNNNNNDN7?===,=~.,,,~8NMMMMMM7?+==+=+?++=:,7:ZNNI:,:,,=I7~7I+MMM?7$8=+O=DZIZI8ONZN=77?7....
               ..:~..,$~~===+$D87?+===,=,$DDNNNNNNNNNNDNI??::,~=,::=+INNMMMMMNO7I=+I,,.,.,.I,~NMM=::,,::DO7+,$7+NONN8Z~+=I?~~++7?$$D....... 
               . ....I...888DDDD?III+==+=+=8NNNNNNNNNNM$:=78DNDDNNMMNMMMMMMMMMMOII7=:~=...,~:NMM787OOO7MMM=$M77NM$MOO+~++I~~~+?7?Z8M:.......
               .....,..+?8888888DDDDDDNNNDDDDNNNNNNNNNNMNNNNNNNNNNNNMMMMNNO887?7I?O~+=+,.,I~7NMMD::::8MMMMMMMMM8:=7I~,::II77I,NN$.. ..      
               ......:==~888888D8DDDDNNDNDNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMNMOMN$8Z??O~+=+,,,N~NMNDZ7++8Z~NNMMMMNN=:=?I~:,+??I$$$DMM... .      
               ..$88ZOO8ODD7$ODDDDDDDNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMM7+=~=~~=+O:,,,~M7M$$$7$+$$$Z=DDMMMM+=:==?+,==$II$$Z,MN$.. ..     
               ..Z==:7$$8+87IDDDDDDDDNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMNNDOZNNNDD:,,,?DMDIZ7I7Z$$$D7$$MMN8O~:==??=~~OII7ZZZN8D,.:I$.    
               ..O==:$$ZOOD8D8DDDDDDDNNNNNNNNNNNNNNNNNNNNNNNNNNNN8DNNMMMMMMMMNMMN$~::,,:,D8MM8OO~8NN:=8=7DMMZDN:,~=I$~~~$III$ZZIDDZ......   
                ,ODD?O88ODDDDDDDDDDODDDNNOODDDDDDDDD$I$D8I7?IZ$IINNNNNMMMMMMM7I??OD,???I?NNMMMMMIM8:Z7I77$M8MNI:,~=7$~~:+III$$ZI8DD...      
               ..,..,~=NDDDDDDDDDDN877IIII??++==~=~~$7?::=+:+?=IDNMNNMMMNNNNNNNII$,D,+II77MDMMMNNM~I?II777MMMM~:,=?7$~~::III7$Z$D8D...      
     ....... ..=7$,.,?:Z8DDDDDDDDDDNN877I+=~=::~~=......,=+.?,$ONNNNNNNMNNNZDOII7?I7I?77MIMMMMM78D:=~III7+MMND+:,+?7$~::~+III7$$D+D.........
   .  .....,,,,..,.:O8+?I8D8DDNDDDDNNN88I==~~..+.........,,~DDNNNNNNNNMMNNNNNIIII+NM$I:NON=NNMMM8Z=?,+=77?MMM==:~+?I$~~~~++??I7ZM.M.........
   ..,.,~~...........?+?Z8DDNNNNDDNNDNDNDDI,..........=:=+?DNNNNNNNNNNNNZZOZZ$7I$+DO$7IO~II7ZN8:M::,,+=7I7MM?+~~~?I7$~~~~+++?77ID=7,77$7$77.
  ....,++++I+.......,?++?$8DDNNNNNNNNNNNNNDD7:,,.....,:ODDDNNNNNNNNNNNMNO8OZOZ$7$$II??I7+++7IZ?Z?I~::+=77OM+++:,=7NMD=~++?+=:::~==?7DODID...
  ..D.++++++?7I......+++?788DDNDNNNNNNNNNNDDD8?7?=,,??DDNMNNNNNNNNNNNNN$D87I??I?IIIII?O:==I+?O$Z7$:~~~~7I88I=+::+$DOZ+=++?++~~~~===7DZ?ON...
 ...O7?+++++??Z8 ....+????IIODNDDDDDNNNNNNNNNNDDDDDDDNDNNNNNNNNNNNNNN8IIDN7IIIIIO7I$:DZ?+7III$IIII,::::I?8Z++=::+=.,........,,:.............
77$:.~==+~=~,,$OO=..,+++I??I7D$ODDDDNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO.?+O?:DNMZN=I???+M:++$$7I777IIII??==~ZI+=~:,,++77::::??+III8N..... .    
=:~:~~+=?~~~?,=Z?DM..$Z???IZDDNN8DDDNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNMNMZ77$I7?,,:.O7+=+?88DO7I+=~,,,:~~DI++::=~?+7I~:::+++IIIDN.....      
:....~=~$=~::++:,,.D.,,,,?8DNNNNDDDDNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNM8$ZNO??=,.,8.~=+==+II77+~=?==.=+M7++:::=??7+~::~+++II7DD.:,~=~::.. 
$I~~~+II7Z+:,==++?=DD,,::,8DDNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNN$==??..7..:===~:8$Z8DNMMMN$IOM7+=::,=??$~:::~+??77OD8.,...... . 
.,O????=:OZ:,=~+++ZI8,=NO+IODNDDNNNNNNNDNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNI+==+=,,+,.~===:+8MNMMMDNNO$$MMI+~::,~??$~~~~=++IIIDDD........   
..O?+?++?88~:++I7:$:7DDDD8DOD?~=78DNNNNNNMDNNNNNNNNNNDNNNNNNNNNNNNNDDDDN7II:==8??:8,.,====,N=NOO88$III7OMMI+~::,=???~~~~+++77ZND8,:...      
.,$??+~=IOZ+I~.,.$$~~8I8D~N~=:::,+$ZNNDNNNNNNNNNNNNNNNZ8ODDDDD8DDDDZO8O8ZI+=+OII?$,,,~==+?N+$:::,:=?II?8MM7+:::,==7==~~~++?77N,NO7$...      
I?+,I+==+O++OZ~:,?~O=I.:I?D~I7+=:I$D8NNDNNNDNNNDI+NND7N88DDDDDDDDDDOOO8D:+~:$7:,O?,~==++NN8~,,,.?I?+::,DMMZ~:,,:+=$==~=~??I$NNIN$Z7...      
.I$7I+++~Z?=Z87:,7:,7=IZDNN=+IZDNM7~DNIDNNNNDDZDNNMNDNOD8DDDDD8DDDDZNNN==++I+::I8,=====DD$~::,,,++?I~:~DDDO:,:~~+++?=~?IO7Z8ZZMN.Z,.I$      
.87II???=I$+?I$~~O:::+8ODNN~=~~8$$7I7$8NNNNNNNNODNNNDNDNDNNNNNNNNDNNNI?++?M$7I=N~==~=:~:Z+~::~=:+??7IOZ7:,~:~::=++:~~=~=?7ZMMIN8$Z$?.       
.87II???+,O?=$D7:O:,:ID?88D~+++8$Z7OOZDNDNNDMMD7NNNNDDNNNNNNNN8I?I8N:+=+$NNN7IND~+==:..NN~~:8NNZ~=~8MMM~::~::::?++::==~=+$$$.~~+$Z$=..      
.D7II???~,+?==$8:?,,:$7$?++?=+=8$$Z7777$8NN8NDDDNNNNDDDDDNNNNNO7?7?:==$MNNMN7ON:+==:,,+==+?7NMMN?++8NMMI:~:::::++:~::::+I7$$=7Z$Z,...       
.D777I+~+,,=?Z$?~:::.8?NN+=~,,~~7DNNNMNNNND7N8DDDDDZDDDDNNNNNNNNO::+IMO7IIIZII+=~:II7+$I~~=?DNN?=~:~$88N$7I~=+7I7==~~:~?I$7??NNO,...        
.8$7I+,,+:,,+~=~++::.NDZN+::.~==+ZNM7$ZZZ8NN8N$8OOZIDD8O88D8NNNO:=:NM7II77I~I,,::::~?++~:::?II~,,,,,I77ZMN~~+=ZI+=====?IZOON.77I.:. ..      
.O$I?::,=~,,+===~+?:,78ODO::,,,,ODN7N8DD8DDDNNN87777IONNNMNMDN~~~MZNMMNMMM=:?:,~Z.8NMO:,,,?III?,,,,~I7$7MM::~+I7======IOOMOD.7$7. ....      
.8Z++~::+=:,,,,D8:~Z=+I:ND~,,...7N=~D8D8DDNNNNNNNNNNNNNNNNNMI~~:ODMMMMMNM=DZN?D~IMOON+??==+===+,,+OI?7$8MM:,:$II==++==?ZZNZN.$7$:...... .   
.8I++==~++:,,,,O87OO7+??ON~,,,.,~D$Z$OZZZZNNNNNNNN+=+~::DNMN$7??OONMM++?O$MMN++MMO7II::.===~=++,++88:~MMMZ:~~7I==+?+??7OND8N.IO$.........   
.OI++===++,,,,,$8:.:N++??D~:,,...:==DD87IZNNNNNNNNDMDNN=I$ZZODNN7NNZ8$$ZZONMNMMMMNI+=:~,=~~~~~+~I~OO~+MMM~::7I?===I+++=NNOD8,7Z8..=:::7. .. 
.$I++====+:,,,,IDZ..N7?+?II:,,,..,,~~=+NNNNNNNNNNNNNN:I7777NNMMNNDN+$$$$ZI$7MMMDM::,,=,:+?+=~~,:?+ZO=NNNN:,:I?~:~=?++?=NNZNO,IDZ.?ZZZI. ... 
.$I++===~+:,,,,$8?..,N?++?Z=,,,....,~~,+DNNZZZO8888Z$$7$NNNNNNII$8M7++=:+?I~DNI:::,,,,:????=~:++:8D$$$$$??:7?+:::+7?I77DND=Z :7?.77$$7.  .. 
.+I+===~~+~,,,:7D=...NZ+==?~~=~,::Z8787DD8N8D8DDDDDDNMNNMMMNMZ7I7N=+=~=?+I,ZDM~:::,=$8ND$$$+=MNN+DNDDNDI+=,7I::::~8$ZZIOZMID7I~, ,?7~.      
.=I++===~+~,,::,O:...IN+++?~==:,I?$78Z7ZZZZ8D8DDDDDDNMNMMMMNNNZZZ~==~?+?=,I7I??III?7NDDMNNM88NNMIIZNDDD7?,??+:::I:87$7?OZNZ$OI~~......      
.~7??===~++::~~+I7.....Z?+=?D=:,ZINNZ:,,+I7NNNNNNNNDNMMNMNND8I$,=+=+??O,=?+ZZ$ZZZZ7Z?~:~NMNMZMNNZ~:7Z8$~::II::,~=:OIII+O8DMO+:+=......      
$+====+==+?+$ZZZ$I7N...DI=++$N?~:NI:.,,.=III777I7777NMNNNDI?I:,:==$IDMN~==77=,:,::~::?7IDNNM=8DD=::~::8:,I?.:::O~=MM$OD$7IO~~?8Z:           
7+===~===~+?????IIIO8..:DI+==ON+.7+=.~..:?IIIIIIII77M8N$?I:,,~:?M$MMMM7=+=IO~:~~==$$?I$I$7O$Z+7.7IN7N778++$+I$ZDNMMM$DN777O?$MMMN.....      
..Z?+++==~+I??III7I.D...+O~=~=8D.+==.Z,,:??I??I??+NNN77I::::7MMNMMMND=++=I~Z=~~~=~I?~=+??$7DNNDM$NNONNNO::7$MD$DNNN$O8N777Z++~++I,.. .      
..$?+++==~+I7$I::+~I..,.,Z?::~~8Z+==.D,,,??I,...8NMDND7?+7NNMD$OOOD+~?+=77D:~~~~~::::$O888O=+$7N$+O7:IDZI7I==M+==Z8~Z?I?+=I++=777.......    
..7?+++===+=,,=:~~~?.....,7:~=::Z+=:OD,,,??I,+?II=?I?,II8NMNDNI+M7OM7M=7IDI~:,,:,,:?MNMZ??IINMMM7I?M:,II~,,~~=MMM8=I+$MD$II~,IIII,.. .      
..:?++++===+,:~.Z?.......,+~~+,,:$..NN:,,??I:7Z8+77Z?===ZO7NMDO8D8Z7$Z77NMM~7D+IIII8N?ZO7II?NMMMMMM8~+++,:+=IMMM$~=:?DM$7?=,:IIII~.. .      
...7?+++==~+:::,7=.......,+~=?,,,:$ID7,,,?IOMNMMONNM$ZZZ7D?=NMM$:::DMMMMZ??O==N$O???~O+=8MMMMNNN8NM++?+::?,+MMM$?=~ODM=~++~:,?III,.. .      
...$??+?+=~+:::,=~........?~++,::~:NN.,:,?IDNNNM$OODI77$IMIMMO~~?MNMMMMM$OZZ?+DNOONN~~=:I$??++++$NM~??:=I:DMMM$$Z$MMMZ~=+?+~,+III,..........
...+I++?I=++=::,.=.......,::,8DD$??88:,:,+II$O8ZOOOOII78ZN8O8O$$D7ZDNMNN$$O$??:+N:?=8:+IMMD?~=?IDM$7?:~I+DNMM=$$DMMN8?=++??+~:::::..........
...,Z+?+??==+?::.I.=,$Z..Z..:?887++Z+?????++~~II?IIDNMM$O8NNDN78::,:?8NMNN=+IMM?=~:NNM=8NMO+=~++NN7?~:~=MDMM+~7DMMOM$$I=+IIZ7~~==?7::,7.....
...,7?I?+?==+:,:.7.=,$7..D..II????????+++??::++????ZDNM~:O?++?,=~,??II78~88NM7NN=~INN?N+Z$~~:::DMDI?:,:$NMM~~=MMM$M+$77~~I+8==++7I7+:.$..:..
:,.,.=+$?+==+=::,:,......N7ZZ$$ZI+:::::~=+==~::=====??I77===++:?77+==I78NZ?~:=I~=7M+:I=::~+?I?~MN??=:?+IMM+?OMMNZD~+77Z=~,+III?=~~:=..... . 
~,,,,++$I++==+::,.I......8I+::::,:~=$$NNNNNNNN?+===++??I?I???I7~=7=+=7:~DOO+=7~I7~:++I+=$MMMMMNMOI+?N8DMM+$MMN8$++=?7NM=??O~~,$=O++=.....   
.....Z=7O+?==+~::.8...,:~::?.....=~$NODNDNNNNNZ++===???I??????+OD:7ZD+8N=NDO7I=$7+=+?I+8MMMMMMMM?77MMMMD+$MMM$~8????+DN.ZOI+=+=?+D+.... ....
    .Z+$8??+=+=::.Z..+=,,==$:,+?,~I..$DDNNDDD$+7~::+=ZZZ=,,:~:I7M=?~=$==$I=7ZZMZN~..~=+ONNNNNNMNZMMMNND+7MMNO=7I....77+. ,I,,,,..?... ...   
    .Z?7OZ??=++~:.++,~===~=I,,?+II~??~=~7DNDN8?N~~~=,=:7~::=++?Z~?..,:,:II+~7OOZNN::===:+~::~MM+NNNNMZINDDN$$77$~=~~.?~,..........$,.....   
     ..OZO??+=+=::.O..,....:?=+?88?~~7??,=$,,=IZ=~:I?:~N~:::=+NN=Z:,,:O+~N?~$$DNNZ::::=:,:::MMDMMMODDDD8ZZZZ$~I7:=?,:O$?NN?..............   
     ...78I??=+=~:.8+. ...=?DD.,?O?+~+II::::?$I:?+?D:I?OZ$?+=+?II:,,,=~:~:~8D=:~~:???+??:::$MMNMMM$D8887II??II+?Z8DM7IZZDOIZ=.+~?7I...      
      ...?ZI??+++~,?O.....I?:.,?887==7OO?II+=,:7I=?:7??DND$I7$I:.?~?I=MMMM=~=,,,,~???+:,::~MMMMMN$8D888$I???I=~:DND8=I?IZ+=I...=I..=,.      
    .....+NIII+?+=..O.....II?++++?IO88D8D$I?$DO7=++O+??N$I$++:=,:?I??+8DDZ8:~,,,,:???:::::NNMMMD~8N7MI+?$Z$+:~~~$?+=,~=:=.:,...,.==~~.      
    .....,OO77????=.O~....?I??+???I88D88O??7OZ+I$7$N~?+8$7?:7,?7$=++===~=,,::,,:::I??:,:,=MMMMZ?DM=M===I$7$7==++=~,:::~::..=~+==,==~=.      
          .MZZ,.....++.8.I?+Z...+IZ,III=:,??:+?I7$OIMI?8I7++7++I?+78D87+=::~+?II77III~,:=MMMNZ+D7I$~~===$$$7$$88$=~~~~~~=MONN?+=+..+.,=.    
           ,NZZ$7I?~.8~...,..,,,Z?II?Z:::++?I+I7II$$NI7II7=$$+??I8NNNNM?I77777777777:::~+NDN?IM?N::~~==+=?+7I$DND+++++++?NDNMI...,,+,,=     
          ..+8Z$I??+:DD......,,:?===:,,:~+??I+7.?.,ZO$Z7==ZII$+$$$DNN87=?I77777III?:::~=NND+D7?7.,.:+~+I++?OOD$MM7+?I====8O$7ZNM~.,...: .   
          ...7Z$$+I?.ZDI.....,,,+???~::~==7777~.$7IN=+=??I+ZOIII+DDMN?+=~+II??=~,,:::~=ZD?=~.8 ..ONMN,=NMM7?8O$D8?++~:....... ........:..   
          . ..DOZ$:I?.MM.....,:,~?II~::==~I??+7?+++I??7+I7OONNNDDNNNM?+=~::,,:~:~~~,~,,MIO.,,....NDDM..7MDI~88I$=~==+?........,:~,....:..   
          ...,.8$77.?,NM$888Z8I+~::,:::==~$????$7$7$Z$OMNNNNNNNNNNNNN+==~~::~+~~::~...M...$...:.,:M8DDN$O?+7?I+Z7++7$$I..,~~~==========.... 
          ... ..8$$7~?+888D8.+=77+...::==~==+?ZOZZO7MD?:IZZZOOOO87DO7+=~~~~I7777+ ...M8.O.IZO~=+???I7I?.==.7+=,DNZ+7I7:+$I....,~~...=~:. .. 
          .. ....Z$$Z$,DDN8D$::::+~:::,.~I$88Z7.?777ZO$ZD7?+++++$O$$7+====?7$$$7I::.$+I,+?$O8ZZZ$ZMNM$.,.,,..,.ODM??7?,+..,......,..:::.... 
          ..  NDDNDOO:I~D8~.. .,....:,..:8,.~Z$,...$$+I7++++++++?$$$ZZZOO7+??+=====7+???I$ZOOOZZZMMMM7$I?8IMZ=~I7ZZ$++$I+I$...8OO=:.:::.... 
.. ......,:...I8NNNZZI77$I.:~::,........:Z,ND,.:N..~N?=N+7$ZOZZZOOOOZZZOOO+++====?:..?II?IZZZ7$OOOMNN:,?+.+=I$$===..+O??$OD...$DN$I........ 
 =,Z$?,I~.+=~=:...?~ZI88$..:IZ$?IZ..., ..O.NN77..O.=+I~N.7ZOO888OOOZOOOZOZ?+++++I?...,I?I?I7I?I$Z7$N$.OOZOZZ=~==?+....IINIZ...ZODON........ 
 ~$+.:.I~:$..~7.,...$7?=7...$~~O~=7II$,~:$Z88O$.?~~8$++O77$77Z:ZO..$,77?III++?II??...=IIIII?????II$NMMMI8ZZZ?++???+?+~,.,.$......$+..:,.... 
.. .............. ...7$$$~MNM...??7$7$,,:ZZ87$D....?ODD?,,~~.?7$O,...?ZO~~I+?+???+,.I7777II????????.,.,,~=~Z7+???+::..~:++.....~=~:........ 
                     .?OZZ=MMD:.$7ZZ$$?,~O7ZO8O:...Z8NMI??+=+OOO8...Z~DO+I+??+????=,~777III???????+.....==~,......?Z=M=7~~~....~~....       
                    ....N$ZIMMZ,,~=?==8D:IZZZOZ~,.,OOZOZ$$7Z,.:O87++=,$$O8$I$Z$ZZ$$?7Z.~???I?+~.............     ...................        
                    .....DZ7=~N..,+?+=:~.IO8ZZ7...=Z$$8ZI?.:I++O8~,...88ZZ78ZZZZZO$$ZZZ.....................     ................           
                         .+NO=.M,.++++:~=+IO$Z7, ..Z?8O8O88Z$+.+:,O...7I8$7.:.+?8I....O.    ......                                          
                         ...OM:.I.+I+?..?=OZ=$+..M.ZI8DZD7$777.....DI:I..=88Z=...?.,.,=     ......                                          
                         ....,88.7,I++...+8.,=?ZD7ID.,.OZ,......I..8...,. .............     ......                                          
                           .....N:=.:==~~~I+++=,:..D7ZIO.Z88II.....Z ..8.. ..$=,$~.. ..      ..?..                                          
                               ..=8.   . .....  .  ......7IZ=......?...? . .+=+==Z.          .....                                          
                                                                                                                                                                                                                                         

-->
<div id="missingno"><img src="missingno.png">
<p>WHITED OUT!</p>
<p><a href="javascript:history.back()">GO BACK TO THE POKEMON CENTER...</a></p></div>
</body>
</html>